### ISSUE TITLE
upload WP users to Chi

### ISSUE THREAD

**Issue by tnorthcutt** [tnorthcutt/member-score-wp-plugin#3]
WP side of https://github.com/tnorthcutt/chi/issues/92

@rclations we _may_ need to make accommodations in the Chi API to allow for this; not 100% sure. Jumping on a call right now but I'll add some details shortly.

**Comment by tnorthcutt** [comment]
Creating the Member records in Chi should not affect the last seen date - in other words, this initial upload should not count as that Member "logging in"

**Comment by rclations** [comment]
built the structure for this minus the API calls here - https://github.com/tnorthcutt/member-chi-wp-plugin/commit/136d6de500114576964b304be8f7f7158094a97e
